const data = [
  {
    id: 9007070,
    name: "Bezmer Air Base",
    region: "Yambol",
    country: "Bulgaria",
    lat: 42.45,
    lon: 26.35,
    url: "bezmer-air-base-yambol-bulgaria",
  },
  {
    id: 1117158,
    name: "Jamshedpur",
    region: "Jharkhand",
    country: "India",
    lat: 22.8,
    lon: 86.18,
    url: "jamshedpur-jharkhand-india",
  },
  {
    id: 1117138,
    name: "Jamnagar",
    region: "Gujarat",
    country: "India",
    lat: 22.47,
    lon: 70.07,
    url: "jamnagar-gujarat-india",
  },
  {
    id: 3116090,
    name: "Jambi City",
    region: "Jambi",
    country: "Indonesia",
    lat: -1.6,
    lon: 103.62,
    url: "jambi-city-jambi-indonesia",
  },
  {
    id: 2318917,
    name: "Jamame",
    region: "Jubbada Hoose",
    country: "Somalia",
    lat: 0.07,
    lon: 42.75,
    url: "jamame-jubbada-hoose-somalia",
  },
  {
    id: 226184,
    name: "Jambol",
    region: "Yambol",
    country: "Bulgaria",
    lat: 42.48,
    lon: 26.5,
    url: "jambol-yambol-bulgaria",
  },
];

export default data;
